version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env

volumes:
  db_data: